spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        '[format_sql]': true

api:
  food:
    base-url: http://openapi.foodsafetykorea.go.kr
    key:
    service-id: COOKRCP01

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE